// @ts-nocheck

export const PERMISSION_RULES = [
  {
    id: "git-push-force",
    scope: "git",
    match: "git push --force | git push -f",
    re: /\bgit\s+push\s+(--force\b|-f\b)/,
    action: "ask",
    reason: "force push",
  },
  {
    id: "git-push",
    scope: "git",
    match: "git push",
    re: /\bgit\s+push\b/,
    action: "ask",
    reason: "원격 저장소 변경",
  },
  {
    id: "git-pull",
    scope: "git",
    match: "git pull",
    re: /\bgit\s+pull\b/,
    action: "ask",
    reason: "원격 refs 및 worktree 변경 가능",
  },
  {
    id: "git-fetch",
    scope: "git",
    match: "git fetch | git remote update",
    re: /\bgit\s+fetch\b|\bgit\s+remote\s+update\b/,
    action: "ask",
    reason: "원격 refs 갱신",
  },
  {
    id: "git-add",
    scope: "git",
    match: "git add",
    re: /\bgit\s+add\b/,
    action: "ask",
    reason: "index 변경",
  },
  {
    id: "git-mv",
    scope: "git",
    match: "git mv",
    re: /\bgit\s+mv\b/,
    action: "ask",
    reason: "파일 이동 및 index 변경",
  },
  {
    id: "git-rm",
    scope: "git",
    match: "git rm",
    re: /\bgit\s+rm\b/,
    action: "ask",
    reason: "파일 삭제 및 index 변경",
  },
  {
    id: "git-commit",
    scope: "git",
    match: "git commit",
    re: /\bgit\s+commit\b/,
    action: "ask",
    reason: "history 변경",
  },
  {
    id: "git-merge",
    scope: "git",
    match: "git merge",
    re: /\bgit\s+merge\b/,
    action: "ask",
    reason: "history 또는 worktree 변경",
  },
  {
    id: "git-rebase",
    scope: "git",
    match: "git rebase",
    re: /\bgit\s+rebase\b/,
    action: "ask",
    reason: "history 재작성",
  },
  {
    id: "git-cherry-pick",
    scope: "git",
    match: "git cherry-pick",
    re: /\bgit\s+cherry-pick\b/,
    action: "ask",
    reason: "history 또는 worktree 변경",
  },
  {
    id: "git-stash",
    scope: "git",
    match: "git stash",
    re: /\bgit\s+stash\b/,
    action: "ask",
    reason: "작업 상태 이동",
  },
  {
    id: "git-tag",
    scope: "git",
    match: "git tag",
    re: /\bgit\s+tag\b/,
    action: "ask",
    reason: "ref 변경",
  },
  {
    id: "git-worktree-mutate",
    scope: "git",
    match: "git worktree add | git worktree remove | git worktree move | git worktree prune | git worktree repair",
    re: /\bgit\s+worktree\s+(?:add|remove|move|prune|repair)\b/,
    action: "ask",
    reason: "worktree metadata 또는 파일 상태 변경",
  },
  {
    id: "git-reset-hard",
    scope: "git",
    match: "git reset --hard",
    re: /\bgit\s+reset\s+--hard\b/,
    action: "ask",
    reason: "작업 폐기 가능",
  },
  {
    id: "git-reset",
    scope: "git",
    match: "git reset",
    re: /\bgit\s+reset\b/,
    action: "ask",
    reason: "index 또는 worktree 변경 가능",
  },
  {
    id: "git-branch-delete",
    scope: "git",
    match: "git branch -d | git branch -D | git branch --delete | git branch --force",
    re: /\bgit\s+branch\s+(?:-[a-zA-Z]*[dD][a-zA-Z]*\b|--delete\b|--force\b)/,
    action: "ask",
    reason: "브랜치 삭제 또는 강제 변경",
  },
  {
    id: "git-clean-force",
    scope: "git",
    match: "git clean -f",
    re: /\bgit\s+clean\s+-[a-zA-Z]*f/,
    action: "ask",
    reason: "untracked 강제 삭제",
  },
  {
    id: "git-checkout-force",
    scope: "git",
    match: "git checkout --force | git checkout -f",
    re: /\bgit\s+checkout\s+(?:--force\b|-[a-zA-Z]*f[a-zA-Z]*\b)/,
    action: "ask",
    reason: "작업 내용 덮어쓰기 가능",
  },
  {
    id: "git-checkout",
    scope: "git",
    match: "git checkout",
    re: /\bgit\s+checkout\b/,
    action: "ask",
    reason: "branch 또는 worktree 변경 가능",
  },
  {
    id: "git-switch-force",
    scope: "git",
    match: "git switch --force | git switch -f",
    re: /\bgit\s+switch\s+(?:--force\b|-[a-zA-Z]*f[a-zA-Z]*\b)/,
    action: "ask",
    reason: "작업 내용 덮어쓰기 가능",
  },
  {
    id: "git-switch",
    scope: "git",
    match: "git switch",
    re: /\bgit\s+switch\b/,
    action: "ask",
    reason: "branch 또는 worktree 변경 가능",
  },
  {
    id: "git-restore",
    scope: "git",
    match: "git restore",
    re: /\bgit\s+restore\b/,
    action: "ask",
    reason: "작업 또는 staging 변경 폐기 가능",
  },
  {
    id: "rm-rf",
    scope: "filesystem",
    match: "rm -rf",
    re: /\brm\s+-[a-zA-Z]*[rRfF][a-zA-Z]*/,
    action: "ask",
    reason: "재귀 강제 삭제",
  },
  {
    id: "find-delete",
    scope: "filesystem",
    match: "find ... -delete",
    re: /\bfind\b[\s\S]*\s-delete\b/,
    action: "ask",
    reason: "검색 결과 파일 삭제",
  },
  {
    id: "rag-bootstrap",
    scope: "rag",
    match: "rag/scripts/bootstrap.sh",
    re: /\brag\/scripts\/bootstrap\.sh\b/,
    action: "ask",
    reason: "RAG DB 초기화",
  },
  {
    id: "rag-add-memory",
    scope: "rag",
    match: "rag/scripts/add_memory.py",
    re: /\brag\/scripts\/add_memory\.py\b/,
    action: "ask",
    reason: "memory 파일 변경 및 RAG sync 실행 가능",
  },
  {
    id: "rag-sync-workspace",
    scope: "rag",
    match: "rag/scripts/sync_workspace_repo_docs.py",
    re: /\brag\/scripts\/sync_workspace_repo_docs\.py\b/,
    action: "ask",
    reason: "RAG sync — 누락 데이터 삭제 가능",
  },
  {
    id: "rag-sync-notion",
    scope: "rag",
    match: "rag/scripts/sync_notion.py",
    re: /\brag\/scripts\/sync_notion\.py\b/,
    action: "ask",
    reason: "RAG sync — 누락 데이터 삭제 가능",
  },
  {
    id: "rag-sync-memories",
    scope: "rag",
    match: "rag/scripts/sync_memories.py",
    re: /\brag\/scripts\/sync_memories\.py\b/,
    action: "ask",
    reason: "RAG sync — 누락 데이터 삭제 가능",
  },
  {
    id: "rag-load-docs",
    scope: "rag",
    match: "rag/scripts/load_docs.py",
    re: /\brag\/scripts\/load_docs\.py\b/,
    action: "ask",
    reason: "RAG 적재 — 덮어쓰기",
  },
  {
    id: "drop-table",
    scope: "db",
    match: "DROP TABLE | DROP DATABASE | DROP SCHEMA",
    re: /\bDROP\s+(TABLE|DATABASE|SCHEMA)\b/i,
    action: "ask",
    reason: "DB 객체 삭제",
  },
  {
    id: "truncate",
    scope: "db",
    match: "TRUNCATE TABLE",
    re: /\bTRUNCATE\s+TABLE\b/i,
    action: "ask",
    reason: "테이블 비우기",
  },
  {
    id: "delete-from",
    scope: "db",
    match: "DELETE FROM",
    re: /\bDELETE\s+FROM\b/i,
    action: "ask",
    reason: "DB 행 삭제",
  },
  {
    id: "secret-output",
    scope: "agent",
    match: ".env | secret | token | private key output",
    reason: "Secrets must never be printed or exposed.",
  },
  {
    id: "commit-push-deploy",
    scope: "agent",
    match: "commit | push | deploy",
    action: "ask",
    reason: "Publication or deployment requires the user's explicit instruction.",
  },
]
